replicaCount: 1
image:
  repository: ghcr.io/temitayocharles/fintech-audit-service
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
containerPort: 8000
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "250m"
env:
  config:
    APP_NAME: "fintech-audit-service"
    ENV: "staging"
externalSecrets:
  enabled: true
  storeRef: vault-backend
  refreshInterval: 1h
  basePath: kv/temitayo/staging/fintech-audit-service
secrets:
  - envName: ELASTICSEARCH_URL
    secretName: app
    secretKey: ELASTICSEARCH_URL
  - envName: KAFKA_BROKERS
    secretName: app
    secretKey: KAFKA_BROKERS
