replicaCount: 1
image:
  repository: ghcr.io/temitayocharles/autodesk-data-processing-service
  tag: "staging-CHANGE-ME"
  pullPolicy: Always
imagePullSecrets:
  - name: ghcr-creds

service:
  type: ClusterIP
  port: 8081

containerPort: 8081

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
    cpu: "250m"

env:
  config: {}

configMap:
  create: false
  name: autodesk-project-data-processing-service-config

secrets:
  - envName: RABBITMQ_URL
    secretName: autodesk-project-data-processing-service-secret
    secretKey: RABBITMQ_URL

externalSecrets:
  enabled: false
  storeRef: vault-autodesk-project-data-processing-service
  refreshInterval: 1m
  basePath: temitayo/staging/autodesk-project/data-processing-service

ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: autodesk-data-processing.local
      paths:
        - path: /
          pathType: Prefix
