apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argo-projects.yaml
  - platform-tools-app.yaml
  - workloads-app.yaml
  - platform/
  - observability/
  - security/

namespace: argocd
