apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - argocd/projects/platform-observability.yaml
  - argocd/projects/platform-security.yaml
  - argocd/projects/workloads.yaml
