server:
  standalone:
    enabled: true

  extraVolumes:
    - name: tls
      secret:
        secretName: vault-tls
    - name: ca
      secret:
        secretName: vault-ca

  extraVolumeMounts:
    - name: tls
      mountPath: /vault/tls
      readOnly: true
    - name: ca
      mountPath: /vault/ca
      readOnly: true

  config: |
    ui = true

    listener "tcp" {
      address       = "0.0.0.0:8200"
      tls_cert_file = "/vault/tls/tls.crt"
      tls_key_file  = "/vault/tls/tls.key"
    }

    storage "file" {
      path = "/vault/data"
    }

    api_addr = "https://vault.vault.svc:8200"
    cluster_addr = "https://vault.vault.svc:8201"
