apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: discord
  namespace: observability
spec:
  route:
    groupBy: ['alertname']
    receiver: 'discord'
  
  receivers:
  - name: 'discord'
    webhookConfigs:
    - url: 'https://discord.com/api/webhooks/14667372935021856/CXzqqwVHZZ0NgX1LLWYZEQJwJ54Lx5DGxGi3my9sj1plAs3cDBL6eeWWtfTpc1OxY2MB'
      sendResolved: true
